from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.signin,name='signin'),
    path('signup',views.signup,name='signup'),
    path('index',views.index, name='index'),
    path('admin',views.admin,name='admin'),
    path('demart',views.demarts,name='demart'),
    path('demartstationary',views.demartstationary,name='demartstationary'),
    path('skincare',views.skincares,name='skincare'),
    path('cleaner',views.cleaner,name='cleaner'),
    path('chocolates',views.chocolates,name='chocolates'),
    path('electricals',views.electricals,name='electricals'),
    path('kitchen',views.kitchen,name='kitchen'),
    path('spencers',views.spencers,name='spencers'),
    path('about',views.about,name='about'),
    path('feedback',views.feedback,name='feedback'),
    path('loggout',views.loggout,name='loggout'),
    path('product',views.product,name='product'),
    path('cart/<int:id>/', views.carts, name='cart'),
    path('cart/increase/<int:id>/',views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:id>/',views.decrease_quantity, name='decrease_quantity'), 
    path('add_to_cart',views.add,name='add_to_cart'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('order_now/<int:id>/<int:ids>/',views.order_now,name='order_now'),
    path('order_confirm/<int:id>/',views.order_confirm,name='order_confirm'),
    path('order_list',views.order_list,name='orders_list'),
    path('update_order_status/<int:id>/', views.update_order_status, name='update_order_status'),
    path('cancel_order/<int:id>/',views.cancel_order, name='cancel_order'),
    path('shipped',views.shipped,name='shipped'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('dashboard_customer',views.dashboard_customer,name='dashboard_customer'),
    path('dashboard_product',views.dashboard_product,name='dashboard_product'),
    path('dashboard_order',views.dashboard_order,name='dashboard_order'),
    path('report',views.report,name='report'),
    path('setting',views.setting,name='setting'),
    
]