# Generated by Django 5.1.4 on 2025-02-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demart',
            old_name='quantity',
            new_name='stock',
        ),
    ]
