# Generated by Django 5.1.4 on 2025-02-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_quantity_demart_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
