# Generated by Django 5.1.4 on 2025-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_to_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
