# Generated by Django 5.1.4 on 2025-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ordernow_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
