# Generated by Django 5.1.4 on 2025-02-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_to_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
