# Generated by Django 5.1.4 on 2025-02-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ordernow_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
