# Generated by Django 5.1.4 on 2025-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ordernow_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_page',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
