# Generated by Django 5.1.4 on 2025-02-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_signup_page_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_page',
            name='address',
        ),
    ]
