# Generated by Django 5.1.4 on 2025-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ordernow_delete_confirm_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
