# Generated by Django 5.1.4 on 2025-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ordernow_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernow',
            old_name='cart_date',
            new_name='order_date',
        ),
    ]
