# Generated by Django 5.1.4 on 2025-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_cart_date_ordernow_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_page',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup_page',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
