# Generated by Django 5.1.4 on 2025-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_ordernow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='demart_img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
