# Generated by Django 5.1.4 on 2025-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_ordernow_demart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='order_month',
            field=models.CharField(default='February', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='ordernow',
            name='order_year',
            field=models.IntegerField(default=2025, editable=False),
        ),
    ]
