# Generated by Django 5.1.4 on 2025-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_ordernow_order_month_ordernow_order_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernow',
            old_name='demart_img',
            new_name='product_img',
        ),
        migrations.AlterField(
            model_name='ordernow',
            name='order_month',
            field=models.CharField(default='March', editable=False, max_length=10),
        ),
    ]
