# Generated by Django 5.1.4 on 2025-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_demart_img_ordernow_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernow',
            name='order_month',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ordernow',
            name='order_year',
            field=models.IntegerField(editable=False),
        ),
    ]
