# Generated by Django 5.1.4 on 2025-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_ordernow_order_month_alter_ordernow_order_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernow',
            name='order_year',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
