# Generated by Django 5.1.4 on 2025-03-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_ordernow_order_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernow',
            name='order_month',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
